rly_file = "Xmas_2022.rly"
ttb_files = [ "Xmas_2022.ttb",]
ssn_files = [ "Xmas_2022.ssn",]
img_files = [ "Xmas_2022.bmp",]
doc_files = [ "README.md",]
release_date = "2022-12-25"
version = "1.0.0"
country_code = "FN"
factual = false
description = "A casual fun simulation to celebrate Christmas 2022"
year = 2022
display_name = "Christmas 2022"
name = "Xmas 2022"
author = "RailOS Dev Team"
contributors = []
